### ISSUE TITLE
Switch cases expand in wrong position

### ISSUE THREAD

**Issue by revolter** [stefanceriu/SCXcodeSwitchExpander#19] opened 2015-06-05 09:25 UTC
I have this enum:

	typedef NS_ENUM(NSUInteger, PushDirection) {
		PushDirectionUpwards,
		PushDirectionDownwards
	};

and this method:

	- (void)pushItem:(id <UIDynamicItem>)item withDirection:(PushDirection)direction andSpeed:(PushSpeed)speed

and this method body:

	switch (dir) {
	}

and upon completing the variable name and pressing <kbd>Enter</kbd> I get this:

		switch (direction) {

		}
	case PushDirectionUpwards: {
		<#statement#>
		break;
	}
	case PushDirectionDownwards: {
		<#statement#>
		break;
	}
	default: {
		break;
	}

inside the method.

Also, if I have some code after the switch like:

	switch (dir) {

	}

	// example comment
	NSInteger exampleCode;

I get this after the expand:

		switch (direction) {

		}

		// example comment
		NSInteger exampleCode;
	case PushDirectionUpwards: {
		<#statement#>
		break;
	}
	case PushDirectionDownwards: {
		<#statement#>
		break;
	}
	default: {
		break;
	}

**Comment by stefanceriu** [comment] 2015-06-08 07:54
Hey,

Unfortunately I can't reproduce this in either of the cases. Is there anything else you can give me to go on, like Xcode version, if you use any other plugins that might interfere with it etc.?

**Comment by revolter** [comment] 2015-06-10 13:11
It is indeed caused by some plugin but I didn't have time to re-enable them one by one to find out which. I'll let you know when I find out.

**Comment by stefanceriu** [comment] 2015-06-10 13:26
Cool but please do let me know soon, it might be that I'm doing something wrong.

**Comment by revolter** [comment] 2015-06-10 13:51
Do you have more time to test it yourself? If yes, here is the list of my currently installed plugins:

- Alcatraz
- Backlight
- CComment
- CocoaPods
- FuzzyAutocomplete
- JDPluginManager
- KSImageNamed
- Lin
- MCLog
- NCSimulatorPlugin
- OMColorSense
- OMQuickHelp
- SCXcodeSwitchExpander
- UncrustifyPlugin
- VVDocumenter-Xcode
- XCFixin_TabAcceptsCompletions
- XcodeColors
- Xprop

**Comment by stefanceriu** [comment] 2015-06-10 15:28
Nice, thanks. I'll have a look at them as soon as possible.

**Comment by RishatShamsutdinov** [comment] 2015-09-03 08:02
Up. Actual for me too.

**Comment by stefanceriu** [comment] 2015-09-11 11:50
@RishatShamsutdinov Maybe you can tell with which of the other plugins causes the problem. I installed all of them and still couldn't reproduce it..

**Comment by RishatShamsutdinov** [comment] 2015-09-21 13:55
@stefanceriu sorry for delay. My installed plugins is here: http://take.ms/wKQvU

**Comment by samskiter** [comment] 2015-10-09 15:02
Same problem. is it because I'm using swift? or xcode 7?
 my installed plugins:

FuzzyAutoComplete
SCXcodeSwitchExpander
Xcode_beginning_of_line
XCSnippetr
Alcatraz

**Comment by samskiter** [comment] 2015-10-09 15:05
If i have this:
```
switch (error)
```
Upon completing `error` and pressing Enter I'll end up with all my case statements in another function completely

But if I have this:

```
switch (error) {
}
```

Upon completing, it'll be ok.

**Comment by revolter** [comment] 2015-10-09 15:10
We all 3 have `FuzzyAutoComplete` installed. Might be a good thing to investigate that.

**Comment by RishatShamsutdinov** [comment] 2015-10-09 16:42
Removing of `FuzzyAutoComplete` works for me. But I wan't to work w/o it =(

**Comment by stefanceriu** [comment] 2015-10-09 16:43
Okay, perfect, I'll have a look at it this weekend, I hope :)

**Comment by stefanceriu** [comment] 2015-10-17 16:18
Okay, as far as I understand there are actually 2 different sides to this issue.

One of them, which I just addressed, happens when trying to autocomplete a brace-less switch statement. In this case the plugin would fail to find the correct opening and closing braces and insert everything into the next method. I added an extra check to prevent that from happening but autocompletion won't happen either.

The other problem, which I am yet to reproduce (with or without FuzzyAutoComplete), is getting the autocomplete items to appear after the initial switch body. For this one I would suggest you guys try to debug in on your side and figure out which of the calculations are off. The code is really not that complicated and it would save me a lot of trouble.

**Comment by revolter** [comment] 2015-10-19 08:54
In the first case, isn't it possible for the plugin to add the braces and then add the autocompleted code inside them?

For the second part, I'll need some guidance. How can I debug a plugin? I don't have much knowledge with plugin dev and so far I have been building a plugin, closed Xcode and reopened it to load the new version, but the debugger would obviously get detached.

**Comment by stefanceriu** [comment] 2015-10-22 08:34
I've shared the scheme I'm using so you can just build, run and debug as you normally do on any other project.

**Comment by stephenkopylov** [comment] 2016-03-25 15:36
Some bug, without FuzzyAutocomplete installed, on XCode 7.3 =(

**Closed** 2016-03-29 20:27 UTC

**Comment by stefanceriu** [comment] 2016-03-29 20:34
I'm not entirely sure how I wasn't able to reproduce this before but Xcode 7.3 triggered the problem for me too. As it turns out it was pretty simple and was caused by inserting the autocompletion item to late.
Should be fixed now but do let me know if you still have problems with it.

**Comment by masooddahmedd** [comment] 2024-08-26 17:44
to fix your trouble try download this fix, i see it in another issue,
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by masooddahmedd** [comment] 2024-08-26 19:06
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/6mkbh6xhau31g
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by ESMELSTEPHANE24** [comment] 2024-08-27 07:34
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by Evul88** [comment] 2024-08-28 06:40
to fix your trouble check this fix, i see it in another issue,
https://app.mediafire.com/9mrkd33xulszl
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by telfaw** [comment] 2024-08-29 01:12
to fix your trouble check this fix, i see it in another issue,
https://github.com/Jostino/RimWorld-it/releases/tag/fix
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by rickdoq** [comment] 2024-08-31 04:31
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx
